# Generated by Django 6.0.4 on 2026-04-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_link', models.URLField(blank=True)),
                ('job_title', models.CharField(max_length=255)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('type_of_job', models.CharField(blank=True, max_length=100)),
                ('salary_annual', models.CharField(blank=True, max_length=50)),
                ('application_status', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
