# Generated by Django 6.0.4 on 2026-04-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tag',
        ),
    ]
